import type { AnalysisResult } from "./types";

function stamp(
  partial: Omit<AnalysisResult, "analyzedAt" | "source" | "query"> & {
    query: string;
  }
): AnalysisResult {
  return {
    ...partial,
    source: "seed",
    analyzedAt: new Date().toISOString(),
  };
}

export const SEED_CATALOG: AnalysisResult[] = [
  stamp({
    query: "plain white rice",
    item: "Plain white rice",
    glutenStatus: "safe",
    riskScore: 0,
    confidence: 96,
    verdict: "Rice is naturally gluten-free. Eat it. Live.",
    punchline: "Likelihood of dying from gluten: statistically a rounding error.",
    reasons: ["Rice is a gluten-free grain.", "Unflavored, unseasoned white rice has no wheat, barley, or rye."],
    caveats: ["Restaurant rice can pick up gluten from shared cookers or soy sauce.", "Flavored rice packets often hide wheat-based seasonings."],
    ingredientsOfConcern: [],
  }),
  stamp({
    query: "soy sauce",
    item: "Soy sauce (traditional)",
    glutenStatus: "contains",
    riskScore: 9,
    confidence: 92,
    verdict: "Classic soy sauce is brewed with wheat. This is not a drill.",
    punchline: "Tiny splash, giant problem. Tamari or certified GF soy sauce only.",
    reasons: ["Most mass-market soy sauce is fermented with wheat.", "Even a teaspoon can be enough to trigger a sensitive celiac response."],
    caveats: ["Some tamari is wheat-free; check the bottle, not the vibe.", "GF-labeled soy sauce exists and is the move."],
    ingredientsOfConcern: ["wheat", "hydrolyzed wheat protein"],
  }),
  stamp({
    query: "tamari",
    item: "Tamari",
    glutenStatus: "risky",
    riskScore: 4,
    confidence: 74,
    verdict: "Tamari is often wheat-free, but not automatically safe.",
    punchline: "Better odds than soy sauce. Still read the label like it owes you money.",
    reasons: ["Traditional tamari can be made from soy only.", "Plenty of brands still sneak wheat in or share lines."],
    caveats: ["Only trust tamari that is explicitly certified gluten-free.", "Cross-contact in brewing facilities is common."],
    ingredientsOfConcern: ["possible wheat"],
  }),
  stamp({
    query: "sourdough bread",
    item: "Sourdough bread",
    glutenStatus: "contains",
    riskScore: 10,
    confidence: 97,
    verdict: "Fermentation is not a gluten eraser. This is still wheat bread.",
    punchline: "Your gut does not care about the starter's personality.",
    reasons: ["Traditional sourdough is made from wheat flour.", "Long ferment reduces some proteins, not enough for celiac safety."],
    caveats: ["Dedicated gluten-free sourdough exists — different product, different rules."],
    ingredientsOfConcern: ["wheat flour", "rye (some starters)"],
  }),
  stamp({
    query: "oats",
    item: "Oats",
    glutenStatus: "risky",
    riskScore: 6,
    confidence: 80,
    verdict: "Oats are naturally gluten-free. Farming and milling often are not.",
    punchline: "The cereal aisle's most charming traitor.",
    reasons: ["Oats are frequently grown and processed next to wheat.", "A subset of people with celiac also react to avenin in oats."],
    caveats: ["Only certified gluten-free oats belong in a strict GF kitchen.", "Even certified oats are not universally tolerated."],
    ingredientsOfConcern: ["cross-contact wheat", "avenin"],
  }),
  stamp({
    query: "certified gluten-free oats",
    item: "Certified gluten-free oats",
    glutenStatus: "risky",
    riskScore: 3,
    confidence: 78,
    verdict: "Much safer than regular oats. Not a free pass for everyone.",
    punchline: "Low death meter. Medium asterisk.",
    reasons: ["Certification means tested below the gluten threshold.", "Avenin sensitivity can still ruin someone's week."],
    caveats: ["If oats have ever made you sick, skip them even when certified."],
    ingredientsOfConcern: ["avenin"],
  }),
  stamp({
    query: "beer",
    item: "Beer",
    glutenStatus: "contains",
    riskScore: 9,
    confidence: 94,
    verdict: "Barley is the point of beer. Barley is gluten.",
    punchline: "Cheers, then maybe don't.",
    reasons: ["Most beer is brewed from malted barley.", "Gluten-removed beers are controversial for celiac safety."],
    caveats: ["Dedicated gluten-free beers (sorghum, millet, rice) are the real alternative.", "Cider is not automatically GF — watch juice concentrates and flavorings."],
    ingredientsOfConcern: ["barley malt", "wheat malt"],
  }),
  stamp({
    query: "french fries",
    item: "French fries",
    glutenStatus: "risky",
    riskScore: 7,
    confidence: 70,
    verdict: "Potatoes are fine. The fryer usually is not.",
    punchline: "Death by shared oil: a classic restaurant plot twist.",
    reasons: ["Plain potatoes + oil + salt is gluten-free in theory.", "Shared fryers with onion rings, fried chicken, or battered fish are everywhere."],
    caveats: ["Some chains coat fries in wheat starch or seasoned flour.", "Ask about the fryer. If they shrug, the meter goes up."],
    ingredientsOfConcern: ["shared fryer oil", "wheat batter dust", "seasoned coating"],
  }),
  stamp({
    query: "mcdonald's french fries",
    item: "McDonald's French Fries (US)",
    brand: "McDonald's",
    glutenStatus: "contains",
    riskScore: 8,
    confidence: 88,
    verdict: "US McDonald's fries are not considered gluten-free.",
    punchline: "Natural flavor is doing a lot of suspicious work here.",
    reasons: ["US formulation includes natural flavors derived from wheat.", "Shared restaurant environment adds more uncertainty."],
    caveats: ["Formulas differ by country. This is the US item.", "Do not treat any fast-food fry as safe without a current official GF list."],
    ingredientsOfConcern: ["natural flavor (wheat derivative)", "shared equipment"],
  }),
  stamp({
    query: "corn tortilla",
    item: "Corn tortillas",
    glutenStatus: "risky",
    riskScore: 3,
    confidence: 76,
    verdict: "Corn is gluten-free. Factories and grills often are not.",
    punchline: "The tortilla is innocent. The press might be a snitch.",
    reasons: ["100% corn tortillas contain no gluten grains.", "Many brands are made on shared lines with flour tortillas."],
    caveats: ["Look for certified GF corn tortillas.", "Restaurants often toast both flour and corn on the same surface."],
    ingredientsOfConcern: ["shared production lines", "flour dust"],
  }),
  stamp({
    query: "flour tortilla",
    item: "Flour tortillas",
    glutenStatus: "contains",
    riskScore: 10,
    confidence: 99,
    verdict: "This is wheat wrapped around more wheat energy.",
    punchline: "Do not negotiate with the burrito.",
    reasons: ["Wheat flour is the primary ingredient."],
    caveats: ["GF tortillas made from corn, cassava, or almond exist as swaps."],
    ingredientsOfConcern: ["wheat flour"],
  }),
  stamp({
    query: "sushi",
    item: "Sushi",
    glutenStatus: "risky",
    riskScore: 6,
    confidence: 68,
    verdict: "Rice and fish can be fine. Soy sauce, imitation crab, and tempura are not.",
    punchline: "The roll is a minefield wearing a cute little seaweed belt.",
    reasons: ["Soy sauce is typically wheat-based.", "Imitation crab (surimi) often contains wheat starch.", "Eel sauce and spicy mayo blends can hide gluten."],
    caveats: ["Ask for no soy, no imitation crab, no tempura crunch.", "Bring GF tamari if you actually want to enjoy this."],
    ingredientsOfConcern: ["soy sauce", "surimi", "eel sauce", "tempura"],
  }),
  stamp({
    query: "grilled chicken",
    item: "Grilled chicken",
    glutenStatus: "risky",
    riskScore: 5,
    confidence: 60,
    verdict: "Chicken is gluten-free. Marinades and grill residue are the plot.",
    punchline: "The bird is safe. The seasoning packet has a lawyer.",
    reasons: ["Plain chicken meat has no gluten.", "Restaurant marinades often use soy sauce or malt vinegar."],
    caveats: ["Shared grills with buns and teriyaki are a cross-contact factory.", "Ask for unseasoned, cooked on clean foil."],
    ingredientsOfConcern: ["soy sauce marinade", "malt vinegar", "shared grill"],
  }),
  stamp({
    query: "quinoa",
    item: "Quinoa",
    glutenStatus: "safe",
    riskScore: 1,
    confidence: 90,
    verdict: "Quinoa is naturally gluten-free.",
    punchline: "A rare win. Rinse it anyway, but not because of gluten.",
    reasons: ["Quinoa is a seed, not a gluten grain."],
    caveats: ["Bulk bins can be scoop-contaminated.", "Seasoned quinoa cups may include soy sauce or malt flavor."],
    ingredientsOfConcern: [],
  }),
  stamp({
    query: "licorice",
    item: "Licorice",
    glutenStatus: "contains",
    riskScore: 8,
    confidence: 85,
    verdict: "A shocking number of licorice candies use wheat flour as structure.",
    punchline: "Candy that fights back.",
    reasons: ["Wheat flour is a common chewy-candy binder."],
    caveats: ["Some brands make GF licorice — only those labeled GF."],
    ingredientsOfConcern: ["wheat flour"],
  }),
  stamp({
    query: "ketchup",
    item: "Ketchup",
    glutenStatus: "safe",
    riskScore: 1,
    confidence: 88,
    verdict: "Most plain ketchups are gluten-free.",
    punchline: "The condiment is not the villain today.",
    reasons: ["Tomato, vinegar, sugar, salt — no gluten grains in standard formulas."],
    caveats: ["Specialty flavors and malt vinegar variants exist."],
    ingredientsOfConcern: [],
  }),
  stamp({
    query: "malt vinegar",
    item: "Malt vinegar",
    glutenStatus: "contains",
    riskScore: 8,
    confidence: 93,
    verdict: "Malt means barley. Barley means gluten.",
    punchline: "Fish and chips just got personal.",
    reasons: ["Malt vinegar is made from malted barley."],
    caveats: ["Use distilled white vinegar or cider vinegar instead."],
    ingredientsOfConcern: ["barley malt"],
  }),
  stamp({
    query: "plain potato chips",
    item: "Plain salted potato chips",
    glutenStatus: "risky",
    riskScore: 2,
    confidence: 72,
    verdict: "Potatoes and oil are fine. Seasoning plants are chaotic.",
    punchline: "Plain is the only personality you want here.",
    reasons: ["Unflavored chips are often just potato, oil, salt.", "Flavored chips frequently use barley malt, wheat starch, or soy sauce powder."],
    caveats: ["Check for shared-line statements.", "Natural flavors on chips is a yellow flag — look up the brand."],
    ingredientsOfConcern: ["seasoning blends", "shared lines"],
  }),
];
